version: 2
jobs:
  build:
    docker:
      - image: warrenseymour/chrome-extension:latest

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install Dependencies
          command: yarn deps

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Prepare CodeClimate test reporter
          command: cc-test-reporter before-build

      - run:
          name: Run Unit Tests
          command: yarn unit-test

      - run:
          name: Publish CodeClimate coverage report
          command: cc-test-reporter after-build --exit-code $?

      - run:
          name: Build WebExtension
          command: yarn build:web-ext

      - persist_to_workspace:
          root: /root/project
          paths:
            - dist/*

  publish:
    docker:
      - image: warrenseymour/chrome-extension:latest

    steps:
      - attach_workspace:
          at: /root/workspace

      - run:
          name: Replace values in manifest.json
          command: |
            cd /root/workspace/dist
            jq ".version = \"$CIRCLE_TAG\"" manifest.json | sponge manifest.json
            jq 'del(.version_name)' manifest.json | sponge manifest.json
            jq '.browser_action.default_icon = "icon.png"' manifest.json | sponge manifest.json

      - run:
          name: Package Extension
          command: |
            cd /root/workspace/dist
            zip ../casium-devtools.zip *

      - run:
          name: Publish to Chrome Store
          command: publish /root/workspace/casium-devtools.zip

      - run:
          name: Publish to AMO
          command: |
            AMO_ID=eed25b73-3db7-4776-b7e8-bc3133a8ec5e
            JWT_NONCE=`dd if=/dev/urandom bs=20 count=1 2>/dev/null | openssl sha1`
            CURRENT_TIMESTAMP=`date +%s`
            JWT_HEADER=`printf %s {\"alg\": \"HS256\", \"typ\": \"JWT\"} | base64 | tr -d '\n'`
            JWT_PAYLOAD=`printf %s {\"iss\": \"$AMO_JWT_ISSUER\", \"jti\": \"$JWT_NONCE\", \"iat\": $CURRENT_TIMESTAMP, \"exp\": $(($CURRENT_TIMESTAMP + (5 * 60)))} | base64 | tr -d '\n'`
            JWT_SIGNATURE=`printf %s $JWT_HEADER.$JWT_PAYLOAD | openssl dgst -binary -sha256 -hmac $AMO_JWT_SECRET | base64 | tr -d '\n'`
            JWT=$JWT_HEADER.$JWT_PAYLOAD.$JWT_SIGNATURE

            curl "https://addons.mozilla.org/api/v3/addons/{$AMO_ID}/versions/$CIRCLE_TAG/" -g -XPUT -F "upload=@/root/workspace/casium-devtools.zip" -H "Authorization: JWT $JWT"

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/

      - publish:
          requires:
            - build

          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
